version: '3.9'

services:
  redis-node-1:
    image: redis:7.0-alpine
    container_name: redis-node-1
    command: >
      redis-server /etc/redis/redis.conf
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --cluster-announce-ip 172.29.0.2
      --port 6379
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    volumes:
      - ./redis/node-1/conf/redis.conf:/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.29.0.2
    ports:
      - '6371:6379'
      - '16379:16379'
    expose:
      - '6379'
      - '16379'

  redis-node-2:
    image: redis:7.0-alpine
    container_name: redis-node-2
    command: >
      redis-server /etc/redis/redis.conf
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --cluster-announce-ip 172.29.0.3
      --port 6379
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    volumes:
      - ./redis/node-2/conf/redis.conf:/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.29.0.3
    ports:
      - '6372:6379'
      - '16380:16379'
    expose:
      - '6379'
      - '16379'

  redis-node-3:
    image: redis:7.0-alpine
    container_name: redis-node-3
    command: >
      redis-server /etc/redis/redis.conf
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --cluster-announce-ip 172.29.0.4
      --port 6379
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    volumes:
      - ./redis/node-3/conf/redis.conf:/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.29.0.4
    ports:
      - '6373:6379'
      - '16381:16379'
    expose:
      - '6379'
      - '16379'

  redis-node-4:
    image: redis:7.0-alpine
    container_name: redis-node-4
    command: >
      redis-server /etc/redis/redis.conf
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --cluster-announce-ip 172.29.0.5
      --port 6379
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    volumes:
      - ./redis/node-4/conf/redis.conf:/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.29.0.5
    ports:
      - '6374:6379'
      - '16382:16379'
    expose:
      - '6379'
      - '16379'

  redis-node-5:
    image: redis:7.0-alpine
    container_name: redis-node-5
    command: >
      redis-server /etc/redis/redis.conf
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --cluster-announce-ip 172.29.0.6
      --port 6379
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    volumes:
      - ./redis/node-5/conf/redis.conf:/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.29.0.6
    ports:
      - '6375:6379'
      - '16383:16379'
    expose:
      - '6379'
      - '16379'

  redis-node-6:
    image: redis:7.0-alpine
    container_name: redis-node-6
    command: >
      redis-server /etc/redis/redis.conf
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --cluster-announce-ip 172.29.0.7
      --port 6379
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379
    volumes:
      - ./redis/node-6/conf/redis.conf:/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.29.0.7
    ports:
      - '6376:6379'
      - '16384:16379'
    expose:
      - '6379'
      - '16379'

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
          gateway: 172.29.0.1
